### PR TITLE
Add code for locating settings and resource files.

### PR DESCRIPTION
**Pull request by ghost**
This should work as-is on Windows and Mac. On Linux the filesystem is arranged according to the FHS so Allegro's code will not work. E.g executable under /usr/bin and data under /usr/share/invincible-countermeasure. In that case the convention seems to be to add a #define via the makefile in order to 'compile in' the expected file location.
This PR gives the location as "." so it will work with the launcher created by the current Makefile.

### CODE REVIEW

**Comment by bambams** [comment]
I had intended to clean this up a little bit more to my liking, but I have found myself without the time or motivation. I'll just merge it for now and cleanup can happen later if anybody gets motivated enough. This really is a quite neat game so it would be rewarding to package it up for the creator and get it into a few distributions.

**Comment by ghost** [comment]
If you let me know where you thought it needed cleaning up I can re-work it.

**Comment by bambams** [comment]
Mostly just cosmetics. More white-space, that sort of thing. It's not even my code base, but I'm just OCD.

Ideally I wanted to work on figuring out how to install it into the system too. The idea would be to put shared data files into /usr/lib/invincible-countermeasure, configuration files into /etc/invincible-countermeasure and by default store the user generated files in $HOME/.invincible-countermeasure or maybe $HOME/.config/invincible-countermeasure or something. Or at least something that would be compatible with distributions so it would be easy to package it up...

It sounds like the file dialog API isn't very flexible though so we might have trouble pointing users to the right places, and I also wanted to avoid making too many changes to the source code because it is liking changing upstream anyway.

**Comment by ghost** [comment]
As it stands it will the user-generated files into the right place (at least according to the Allegro API) - on Linux it's `~/.config/invincible-countermeasure/` 

I've had some experience on making packages for Debian and its 'children', e.g. Ubuntu. It's quite tedious but not too difficult. If you use autotools it's a whole lot easier. Actually getting it _into_ Debian might be a lot harder as they're sticklers for the details! 

Finally, I agree with you; the upstream is still likely to change a lot. Therefore I think spending too much time is not worth it, yet.

**Pull request merged**
